@startuml
interface IMp3 {
    void payMp3();
}
class Mp3 implements IMp3 {
    public void payMp3();
}
interface IMp4
class Mp4
IMp4 <|.. Mp4
class PayerAdapter
IMp3 <|.. PayerAdapter

IMp4 <.. PayerAdapter

class Client
PayerAdapter <.. Client

@enduml